p8105_hw1_ec3663
================
Eunsuh Cho
2023-09-19

# Problem 1

## Loading the dataset

``` r
library(moderndive)
data("early_january_weather")
```

## Discussion of dataset

``` r
nrow(early_january_weather)
```

    ## [1] 358

``` r
ncol(early_january_weather)
```

    ## [1] 15

``` r
temp <- early_january_weather$temp
mean(temp)
```

    ## [1] 39.58212

``` r
sd(temp)
```

    ## [1] 7.058637

`This dataset contains weather factors for the first half of January 2013. It has 358 observations and 15 variables, including dewpoint, humidity, wind characteristics, precipitation, and pressure. The mean temperature is 39.58 degrees Fahrenheit with a standard deviation of 7.06.`

## Creating the scatterplot

``` r
library(ggplot2)
ggplot(early_january_weather, aes(x = time_hour, y = temp, color = humid)) + geom_point()
```

![](p8105_hw1_ec3663_files/figure-gfm/p1_scatterplot-1.png)<!-- -->

``` r
ggsave("temp_vs_hour_by_humid.png")
```

    ## Saving 7 x 5 in image
